//! B5: stamp the git revision into the binary.
//!
//! A version number alone cannot say which build wrote a batch — 1.0.0
//! is 1.0.0 for the whole release — and a manifest that records the
//! wrong build is worse than one that records nothing. The revision is
//! best-effort on purpose: a tarball or a vendored copy has no git
//! metadata, and refusing to build there would be a poor trade.

use std::process::Command;

fn main() {
    // Rebuild when the checked-out commit changes. Without this the
    // stamp would freeze at whatever HEAD was on the first build.
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs");

    let rev = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|out| out.status.success())
        .and_then(|out| String::from_utf8(out.stdout).ok())
        .map(|rev| rev.trim().to_string())
        .filter(|rev| !rev.is_empty());

    let dirty = Command::new("git")
        .args(["status", "--porcelain"])
        .output()
        .ok()
        .is_some_and(|out| out.status.success() && !out.stdout.is_empty());

    let stamp = match rev {
        // A build from a modified tree is not the commit it claims, and
        // a batch generated by one must say so.
        Some(rev) if dirty => format!("{rev}-dirty"),
        Some(rev) => rev,
        None => "unknown".to_string(),
    };
    println!("cargo:rustc-env=BPT_GIT_REV={stamp}");
}
