//! M23: the sidecar manifest that describes a batch.
//!
//! Everything a batch cannot reconstruct from its files lives here: the
//! coordinates that reproduce each puzzle (AR28), what was asked for
//! versus what came out, and the fingerprints that let a reader prove
//! the manifest and the directory still agree.
//!
//! Times are passed in rather than read: this crate never touches the
//! clock (AR20), the CLI does.

use crate::grade::Level;
use serde::{Deserialize, Serialize};

/// How a batch ended. A reader must be able to tell a complete batch
/// from a short one without recounting the files (AR29).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Status {
    /// Everything requested was produced.
    Complete,
    /// Fewer puzzles than requested: a level was unreachable, or the
    /// space of distinct puzzles ran out.
    Partial,
    /// Ctrl-C: what was finished is on disk and valid (AR29b).
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub tool_version: String,
    /// The exact revision this batch was generated by, `-dirty` when the
    /// tree it was built from had uncommitted changes. Best-effort:
    /// outside a git checkout it reads `unknown`, which is recorded
    /// rather than omitted so an unidentifiable build is visible.
    pub tool_revision: String,
    /// Which grading ladder produced the levels below. Regrading an old
    /// batch with a newer ladder can legitimately move a puzzle, and
    /// without this field that shows up as an unexplained mismatch.
    pub grading_version: u32,
    pub kind: String,
    pub grid_size: usize,
    pub level_ceiling: Level,
    pub seed: u64,
    pub requested: u64,
    pub completed: u64,
    pub status: Status,
    pub elapsed_ms: u64,
    /// Why the batch fell short, in the generator's own words. Empty
    /// when complete.
    #[serde(default)]
    pub notes: Vec<String>,
    pub puzzles: Vec<Entry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    pub file: String,
    /// The three numbers that regenerate exactly this puzzle (AR28).
    pub index: u64,
    pub attempt: u64,
    pub level: Level,
    pub clues: usize,
    /// Fingerprint of the puzzle line. Not cryptographic — it exists to
    /// catch a directory and a manifest drifting apart, not to resist
    /// an attacker.
    pub digest: String,
}

/// The grading ladder's version. Bump it whenever a change to the
/// strategy tiers can move a puzzle between levels.
pub const GRADING_VERSION: u32 = 1;

/// FNV-1a. Chosen because it is ten lines and stable across platforms
/// and releases; a hash from `std` is explicitly not, so a manifest
/// written today would stop matching after a toolchain upgrade.
pub fn digest(line: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in line.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

impl Manifest {
    /// Render as TOML. The manifest is written last and read by both the
    /// validation harness and a human staring at a failed batch, so it
    /// is a text format rather than a binary one.
    pub fn to_toml(&self) -> Result<String, toml::ser::Error> {
        toml::to_string_pretty(self)
    }

    pub fn from_toml(text: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(text)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Manifest {
        Manifest {
            tool_version: "1.0.0".into(),
            tool_revision: "unknown".into(),
            grading_version: GRADING_VERSION,
            kind: "6".into(),
            grid_size: 6,
            level_ceiling: Level::L4,
            seed: 7,
            requested: 2,
            completed: 2,
            status: Status::Complete,
            elapsed_ms: 12,
            notes: Vec::new(),
            puzzles: vec![Entry {
                file: "bf-7-0-L2.txt".into(),
                index: 0,
                attempt: 0,
                level: Level::L2,
                clues: 14,
                digest: digest("..1.0."),
            }],
        }
    }

    #[test]
    fn m23_a_manifest_round_trips_through_toml() {
        let text = sample().to_toml().expect("serializes");
        let back = Manifest::from_toml(&text).expect("parses back");
        assert_eq!(back.seed, 7);
        assert_eq!(back.status, Status::Complete);
        assert_eq!(back.puzzles[0].file, "bf-7-0-L2.txt");
        assert_eq!(back.puzzles[0].digest, digest("..1.0."));
    }

    #[test]
    fn m23_the_digest_is_stable_and_distinguishing() {
        // Pinned literally: if this value ever changes, every manifest
        // ever written stops verifying, so the change must be deliberate.
        assert_eq!(digest("..1.0."), "3678e64430e2e01c");
        assert_ne!(digest("..1.0."), digest("..1.0.."));
        assert_ne!(digest("0."), digest(".0"));
    }

    #[test]
    fn m23_status_reads_as_a_plain_word() {
        let text = sample().to_toml().unwrap();
        assert!(text.contains("status = \"complete\""), "{text}");
    }
}
